c3p0:
  driverClass: com.mysql.jdbc.Driver
  minPoolSize: 10
  maxPoolSize: 50
#  maxIdleTime: 120
  acquireIncrement: 10
  maxStatements: 1000
  initialPoolSize: 10
  idleConnectionTestPeriod: 60
  acquireRetryAttempts: 30
  acquireRetryDelay: 1000
  breakAfterAcquireFailure: false
  testConnectionOnCheckout: false

spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 10000
    # 连接超时时间（毫秒）
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: -1
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
  servlet:
    multipart:
      # 最大上传单文件大小
      max-file-size: 20Mb
      # 最大上传总大小
      max-request-size: 50Mb
  profiles:
    # 激活dev环境配置
    active: prod

# 多环境配置
---
spring:
  profiles: dev
  redis:
    host: 127.0.0.1
c3p0:
  jdbcUrl: jdbc:mysql://127.0.0.1:3306/qh_dev?useSSL=false
  user: root
  password: root
---
spring:
  profiles: test
  redis:
    host: 127.0.0.1
c3p0:
  jdbcUrl: jdbc:mysql://127.0.0.1:3306/qh_dev?useSSL=false
  user: root
  password: qhhealthserver
---
spring:
  profiles: prod
  redis:
    host: 127.0.0.1
c3p0:
  jdbcUrl: jdbc:mysql://120.78.152.134:3306/qh_dev?useSSL=false
  user: root
  password: qhhealthserver
---

#日志等级
logging:
  level:
    com.hfkd.qhhealth: DEBUG
    logging.level.org.apache.commons.httpclient: OFF

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*Mapper.xml
  type-aliases-package: com.hfkd.qhhealth.*.model
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true #使mapper查询出Map类型的结果空的的键值为null
#    interceptors: OffsetLimitInterceptor

